mcp_can.cpp

The original code reads address 0x31, 0x41, or 0x51 "TXBnSIDH – TRANSMIT
BUFFER n STANDARD IDENTIFIER HIGH".  Because that location points to a
constant value, some of the msg ids cause the program to loop 50 times
and then report a timeout error.  After changing the address to point to
0x30, 0x40, or 0x50 "TXBnCTRL – TRANSMIT BUFFER n CONTROL REGISTER", all
of the messages send out properally with no timeout errors.

Added an offset to the txbuf_n pointer so that the actual ctrl reg value is read.

---

examples/receive_check/receive_check.ino

The ID format wasn't correct. ID has 4 bytes not 1. It was intended to be printed next to the text and HEX format is better to read - that's how CAN professionals work with it.

examples/receive_check/receive_check.ino ID format fix

---

mcp_can.cpp

Force setMsg to clear RTR so it does not use the previous value. Have setMsg copy only as many bytes as necessary. Limit max DLC to 8.

Cleanup on setMsg

---

mcp_can_dfs.h

Fix a typo

---

mcp_can.cpp
mcp_can_dfs.h

Initializes the SPI bus using the defined SPISettings.
Stop using the SPI bus. Normally this is called after de-asserting the chip select, to allow other libraries to use the SPI bus.

SPI Begin and End

---

mcp_can.cpp
mcp_can.h
mcp_can_dfs.h

Hi,
I made several improvements for you library and hope you could update them. I take care of NMEA2000 library and these changes are important, so that it can be used. Now library users sometimes mixes the original version, since for connecting they often use your CAN BUS shield. The library should be still completely backward compatibility and I tested it with your examples.
The biggest change is on mcp2515_write_canMsg and mcp2515_read_canMsg. And because of those I removed some unnecessary private data and functions. That is the main reason for big differences. With these changes I managed to minimize SPI communication so that library communication time dropped half of original.
Note also that with this version I can have full and fast two direction interrupt handled system.
- …

Improved speed, 8MHz clock support, support for NMEA2000 library

---

library.properties

Add library.properties for recognition by the Library Manager.
For more information on the Arduino IDE Library Manager see https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ.
Note: Adding this is useful for installing a folder or .zip file into the library manager even without this being published to be search-discoverable on the library manager.

Add library.properties for recognition by the Library Manager

---

mcp_can.cpp
mcp_can.h

Add a new function storing the selected controller mode. This allows functions switching to various configuration modes to return to the user set mode. Useful if LOOPBACK is used during debugging.

Keep custom controller mode after configuration

---

examples/gpioRead/gpioRead.ino
examples/gpioWrite/gpioWrite.ino
mcp_can.cpp
mcp_can.h
mcp_can_dfs.h

Some of the status pins can be controlled using configuration registers. This additions allow to use them as regular GPIO using pinMode/digitalRead/digitalWrite.
Based on #55 - could also be used with the previous hardcoded style by cherry-picking 0450568699ee11895f963d1ca248652698d1c6ed and changing `mcp2515_setCANCTRL_Mode(mcpMode);` to `mcp2515_setCANCTRL_Mode(MODE_NORMAL);`

Add GPIO-Support

---

README.md
examples/gpioRead/gpioRead.ino
examples/gpioWrite/gpioWrite.ino
examples/receive_sleep/receive_sleep.ino
examples/send_sleep/send_sleep.ino
mcp_can.cpp
mcp_can.h
mcp_can_dfs.h

Added sleep support for MCP2515 + MCP2551. This way, you can reduce the power consumption of a complete node down to around 240uA!
Changes:
- Reintroduced gpio support from commits 43521de/bac66d1 (adlerweb, 15/01/2018) and corrected the errors
- Introduced advanced sleep support based on https://github.com/coryjfowler/MCP_CAN_lib/pull/10/files
- added example code (receive_sleep and send_sleep)
- tested everything

Add sleep and gpio support + examples

---

examples/canbus-monitor/can-serial.cpp
examples/canbus-monitor/can-serial.h
examples/canbus-monitor/canbus-monitor.ino

I created this to help resolve #105 
I do not have an Arduino DUE to test but this does build successfully. Someone with an Arduino DUE will need to verify this actually works.

Use HardwareSerial instead of SoftwareSerial in CAN-monitor example

---

src/can-serial.cpp
src/can-serial.h

Including the SoftwareSerial.h library makes this repo incompatible with the Particle series of MCUs. This library doesn't appear to be used anywhere in this repo. Removing it would improve compatibility with more MCUs.

Removed unused include statement

---

library.properties

Libraries are locked to the `name` value specified by the library.properties metadata file in the release at the time of
the Library Manager submission.
Any release with a different name is rejected by the Arduino Library Manager indexer.
References:
- https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#why-arent-releases-of-my-library-being-picked-up-by-library-manager
- https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name

Revert library name change

---

library.json

Updated `library.json` manifest file to reflect the current release version.  Otherwise this causes PlatformIO Library Manager to load version 1.20 of the library.

Updated libary.json to current version

---

library.json

There was a special character comma after the `MCP2518FD` in the keywords section.  I also updated the keywords to lowercase per the PlatformIO manifest guidelines for [keywords](https://docs.platformio.org/en/latest/librarymanager/config.html#keywords).  These changes did allow the library to package for PlatformIO.  Let me know if you like me to package master as 2.3.0 for PlatformIO or if you would rather do a 2.3.1 release with these changes.  Sorry for all the little nit picky stuff.

Removed special character and updated keywords.

---

src/mcp2518fd_can.cpp
src/mcp2518fd_can_dfs.h

When compiling this library for the Arduino Uno Wifi Rev 2 I found there was a build error with the following output. Using Arduino 1.8.15 for 64-bit Linux
```
/home/qt/Arduino/libraries/Seeed_Arduino_CAN/src/mcp2518fd_can_dfs.h:1466:14: error: expected unqualified-id before 'volatile'
uint32_t GPIO0 : 1;
^
/home/qt/Arduino/libraries/Seeed_Arduino_CAN/src/mcp2518fd_can_dfs.h:1466:14: error: expected ')' before 'volatile'
/home/qt/Arduino/libraries/Seeed_Arduino_CAN/src/mcp2518fd_can_dfs.h:1466:14: error: expected ')' before 'volatile'
/home/qt/Arduino/libraries/Seeed_Arduino_CAN/src/mcp2518fd_can_dfs.h:1467:14: error: expected unqualified-id before 'volatile'
uint32_t GPIO1 : 1;
^
/home/qt/Arduino/libraries/Seeed_Arduino_CAN/src/mcp2518fd_can_dfs.h:1467:14: error: expected ')' before …
```

Fix Arduino Uno Wifi Rev2 and Arduino Nano Every Compatibility

---

src/mcp2515_can.h
src/mcp2518fd_can.h
src/mcp_can.h

Right now, the abstract MCP_CAN class doesn't support the four-argument wrapper for sendMsgBuf. But its definition and implementation is copied and pasted in every implemented subclass in this repo. 
This pull request will move that wrapper to the MCP_CAN class, reducing redundancy.

Move the four-argument sendMsgBuf wrapper to mcp_can.h

---

src/mcp2515_can.cpp

In the method mcp2515_can::checkError(), register EFLG is not reset after tx buffer overflow occurring. I put the code to reset it, so that it will not be error again and again without cause.

Reset rx overflow flag

---

examples/OBDII_PIDs/OBDII_PIDs.ino
examples/send/send.ino
examples/sendFD/sendFD.ino
examples/send_Blink/send_Blink.ino
examples/send_Blink_ROS/send_Blink_ROS.ino
examples/send_sleep/send_sleep.ino
examples/set_mask_filter_send/set_mask_filter_send.ino
src/can-serial.h
src/mcp2515_can.h
src/mcp2518fd_can.h

Maintains backward compatibility with previous versions of the function call by making MCP_CAN::sendMsgBuf visible from the derived classes `mcp2518fd` and `mcp2515`
Now it is possible to compile one or both of the following:
```cpp
CAN.MCP_CAN::sendMsgBuf(0x70, 0, 8, stmp);
CAN.sendMsgBuf(0x70, 0, 8, stmp);
```
Tested by  successfully compiling `send` and `send_Blink` for the Arduino Uno with the `CAN_2518FD` or `CAN_2515` flag enabled

Patch four-argument sendmsgbuf

---

src/mcp2515_can.cpp

Addresses #140 
mcp2515_can::mcp2515_getNextFreeTXBuf() now loops through available tx buffers in opposite order from highest to lowest.
As noted in the original issue, when more than one tx buffer is full, the mcp2515 sends from highest numbered buffer first. This change ensures correct ordering.

Change order of TX buffer fill to ensure in-order sending of frames.
